### ISSUE TITLE
A template to insert (Pandoc-style) rendered citation 

### ISSUE THREAD

**Issue by psyguy** [hans/obsidian-citation-plugin#53]
This pertains to #41 and #42, and I thought it's better to have an issue on its own (btw, I'd like to give #44 a push 😄 too):

I am using @{{citekey}} as note names, but I'd like to use aliases implemented [from v0.9.16 unward](https://forum.obsidian.md/t/obsidian-release-v0-9-16/8795). For instance, for the following `bibtex` entry:

``` bib
@book{macdonald_1997_HiddenMarkovOther,
  title={Hidden Markov and other models for discrete-valued time series},
  author={MacDonald, Iain L and Zucchini, Walter},
  volume={110},
  year={1997},
  publisher={CRC Press}
}
```

have aliases as follows:

``` YAML
aliases:
  - Hidden Markov and other models for discrete-valued time series
  - (MacDonald & Zucchini, 1997)
  - MacDonald and Zucchini (1997)
```

`{{title}}` makes the first line, but cannot think of other templates for the other aliases; something like `[@{{citekey}}]` and `@{{citekey}}`.

Thanks in advance!

**Comment by phlind** [comment]
I'm interested in what you mean, but I can't really get what you want to achieve. Could you maybe explain what you mean with "but cannot think of other templates for the other aliases"? Thanks! :)

**Comment by psyguy** [comment]
Hey @phlind,

I mean, I am looking for a `{{...}}` handlebar/variable that can render citation strings (like `Author1 and Author2, (1990)`; `(Author1, Author2, 1990)`; or (`Author1 et al., 2010)`; etc.).

I can then make something like this in the header template:

``` YAML
---
aliases:
  - {{title}}
  - {{citeRenderPromary}}
  - {citeRenderSecondary}}
---

```

to render this YAML:

``` YAML
---
aliases:
  - Hidden Markov and other models for discrete-valued time series
  - (MacDonald & Zucchini, 1997)
  - MacDonald and Zucchini (1997)
---
```

**Comment by cbr9** [comment]
You can do something like this with Templater :)

This my template:

```yaml
---
---
title: "{{title}}"
authors: "{{authorString}}"
year: {{year}}
zotero: "{{zoteroSelectURI}}"
publication: "{{containerTitle}}"
aliases:
- "<% `${tp.user.authorShort("{{authorString}}")}, ${"{{year}}"}` %>"
- "<% `${tp.user.authorShort("{{authorString}}")} (${"{{year}}"})` %>"
- "<% `${tp.user.authorLong("{{authorString}}")} (${"{{year}}"}). ${"{{title}}"}. ${"{{containerTitle}}"}.`%>"
---
```

`tp.user.authorShort` and `tp.user.authorLong` are the following two Templater scripts (each should go into its own file, and you need to tell Templater where to look for scripts):

```js
function authorShort(authorString) {
  const authors = authorString.split(", ");
  let abbrAuthorString = ""
  if (authors.length == 1) {
      const parts = authors[0].split(" ")
      abbrAuthorString = parts[parts.length-1];
  }
  else if (authors.length == 2) {
      let surnames = [];
      authors.forEach(author => {
        const parts = author.split(" ");
        surnames.push(parts[parts.length-1]);
      })
      abbrAuthorString = `${surnames[0]} and ${surnames[1]}`;
  } else {
      const first = authors[0].split(" ")
      const surname = first[first.length - 1];
      abbrAuthorString = `${surname} et al.`;
  }
  return abbrAuthorString
}

module.exports = authorShort;
```

```js
function authorLong(authorString) {
  const authors = authorString.split(", ");
  let fullAuthorList = [];
  authors.forEach(author => {
      const parts = author.split(" ");
      let str = [];
      str.push(parts[parts.length-1]);
      const name_parts = parts.slice(0, parts.length-1);
      name_parts.forEach(name => {
        str.push(", ");
        str.push(`${name[0]}.`);
      });
      fullAuthorList.push(str.join(""))
  });
  return fullAuthorList.join(", ")
}

module.exports = authorLong;
```

I know this probably isn't perfect, but it's close enough to what you and I want :)
